import type { ClaudeRunnerConfig } from "cyrus-claude-runner";

export type RunnerType = "claude" | "codex" | "opencode";

export interface RunnerConfigBase {
	type: RunnerType;
	cwd: string;
	prompt: string;
}

export interface ClaudeRunnerAdapterConfig extends RunnerConfigBase {
	type: "claude";
	claudeConfig: ClaudeRunnerConfig;
}

export interface CodexRunnerOptions extends RunnerConfigBase {
	type: "codex";
	model?: string;
	sandbox?: "read-only" | "workspace-write" | "danger-full-access";
	approvalPolicy?: "untrusted" | "on-failure" | "on-request" | "never";
	/**
	 * Environment variables to pass through to the spawned process. Defaults to process.env.
	 */
	env?: NodeJS.ProcessEnv;
}

export interface OpenCodeRunnerOptions extends RunnerConfigBase {
	type: "opencode";
	provider?: string;
	model?: string;
	serverUrl: string;
	/**
	 * Existing session id generated by the OpenCode server, used for resume flows.
	 */
	sessionId?: string;
	/**
	 * Linear agent session id used for logging/context only.
	 */
	linearSessionId?: string;
	openaiApiKey?: string;
	/**
	 * Whether the adapter should automatically retry the SSE stream once on disconnect.
	 * Defaults to true.
	 */
	retryOnDisconnect?: boolean;
}

export type RunnerConfig =
	| ClaudeRunnerAdapterConfig
	| CodexRunnerOptions
	| OpenCodeRunnerOptions;

export type RunnerEvent =
	| { kind: "text"; text: string }
	| { kind: "tool"; name: string; input?: unknown }
	| { kind: "result"; summary?: string }
	| { kind: "error"; error: Error };

export interface RunnerStartResult {
	sessionId?: string;
}

export interface Runner {
	start(onEvent: (event: RunnerEvent) => void): Promise<RunnerStartResult>;
	stop(): Promise<void>;
}

export interface RunnerFactory {
	create(config: RunnerConfig): Runner;
}
